### ISSUE TITLE
Curl not working on T-UI

### ISSUE THREAD

**Issue by vigilantemre** [deadrabbit404/ip-tracker#1]
Im installed the script succesfly but im typing "myip" command on T-UI and im getting error:

"Curl inaccesible or not found"

Note: im installed curl on termux.

**Comment by deadrabbit404** [comment]
Thanks for reporting the issue. You get error because you don't have `curl` installed on your android system. Basically, when `myip` is invoke within T-UI, the script will also use the `curl` binary from your android system whereas if invoke within termux, the `iptracker` script will use the `curl` which is inside termux. `curl` inside termux is not visible within T-UI that is why you are getting error.

If your device is rooted, one solution is to install a curl module in Magisk Manager. When I got time I will modify the script to use `wget` if curl is not available on the device, but you need at least one of the two for it to work inside T-UI.
